# Generated by Django 5.2 on 2025-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('Person', 'Person'), ('Company', 'Company')], max_length=10, verbose_name='Type of Person')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('state_of_residence', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investments', models.DecimalField(decimal_places=2, max_digits=12)),
                ('real_estate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_assets', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loans', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit_card_debt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_liabilities', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
