# Generated by Django 5.2 on 2025-05-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_equivalents', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('trade_receivables', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('related_receivables', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('inventories', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_tax_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('bio_assets_fair', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('bio_assets_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_fin_assets_curr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_nonfin_assets_curr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ppe', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('inv_property', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('goodwill', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_intangibles', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('bio_assets_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('equity_method_inv', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investments_assoc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('receivables_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('related_receivables_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('deferred_tax_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tax_assets_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_fin_assets_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_nonfin_assets_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('prov_curr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('acc_payable_curr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('related_payable_curr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tax_liab_curr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_fin_liab_curr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_nonfin_liab_curr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fin_liab_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('prov_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('acc_payable_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('deferred_tax_liab', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tax_liab_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_fin_liab_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_nonfin_liab_noncurr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('issued_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('share_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('treasury_shares', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reserves_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_comprehensive_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_equity_interests', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('revaluation_surplus', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('retained_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
