# Generated by Django 5.2 on 2025-05-17 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_companyfinancials_total_assets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyfinancials',
            old_name='total_non_curr_assests',
            new_name='total_non_curr_assets',
        ),
    ]
