# Generated by Django 5.2 on 2025-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_rename_total_non_curr_assests_companyfinancials_total_non_curr_assets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfinancials',
            options={'verbose_name_plural': 'Company Financials'},
        ),
        migrations.AddField(
            model_name='companyfinancials',
            name='gpt_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfinancials',
            name='gpt_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
