# Generated by Django 5.2 on 2025-05-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_companyfinancials_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfinancials',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfinancials',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyfinancials',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyfinancials',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyfinancials',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='companyfinancials',
            name='person_type',
            field=models.CharField(choices=[('Person', 'Person'), ('Company', 'Company')], default='Person', max_length=10, verbose_name='Type of Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyfinancials',
            name='state_of_residence',
            field=models.CharField(default='Person', max_length=100),
            preserve_default=False,
        ),
    ]
